// ignore_for_file: always_specify_types
// ignore_for_file: camel_case_types
// ignore_for_file: non_constant_identifier_names

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint
import 'dart:ffi' as ffi;

/// Bindings for WhisperKit wrapper
class WhisperBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  WhisperBindings(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  WhisperBindings.fromLookup(
    ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup,
  ) : _lookup = lookup;

  ffi.Pointer<ffi.Void> whisper_init(ffi.Pointer<ffi.Char> model_path) {
    return _whisper_init(model_path);
  }

  late final _whisper_initPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Void> Function(ffi.Pointer<ffi.Char>)
        >
      >('whisper_init');
  late final _whisper_init = _whisper_initPtr
      .asFunction<ffi.Pointer<ffi.Void> Function(ffi.Pointer<ffi.Char>)>();

  ffi.Pointer<ffi.Char> whisper_transcribe(
    ffi.Pointer<ffi.Void> context,
    ffi.Pointer<ffi.Char> audio_path,
    ffi.Pointer<ffi.Char> format,
    bool word_timestamps,
  ) {
    return _whisper_transcribe(context, audio_path, format, word_timestamps);
  }

  late final _whisper_transcribePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(
            ffi.Pointer<ffi.Void>,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
            ffi.Bool,
          )
        >
      >('whisper_transcribe');
  late final _whisper_transcribe = _whisper_transcribePtr
      .asFunction<
        ffi.Pointer<ffi.Char> Function(
          ffi.Pointer<ffi.Void>,
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
          bool,
        )
      >();

  void whisper_free(ffi.Pointer<ffi.Void> context) {
    return _whisper_free(context);
  }

  late final _whisper_freePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'whisper_free',
      );
  late final _whisper_free = _whisper_freePtr
      .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void whisper_free_string(ffi.Pointer<ffi.Char> string) {
    return _whisper_free_string(string);
  }

  late final _whisper_free_stringPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Char>)>>(
        'whisper_free_string',
      );
  late final _whisper_free_string = _whisper_free_stringPtr
      .asFunction<void Function(ffi.Pointer<ffi.Char>)>();
}
